# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.orgAccountant.example.com:
    container_name: peer0.orgAccountant.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orgAccountant.example.com
      - CORE_PEER_ADDRESS=peer0.orgAccountant.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgAccountant.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgAccountant.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgAccountant.example.com:7051
      - CORE_PEER_LOCALMSPID=OrgAccountantMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/orgAccountant.example.com/peers/peer0.orgAccountant.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgAccountant.example.com/peers/peer0.orgAccountant.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.orgAccountant.example.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.orgAccountant.example.com:
    container_name: peer1.orgAccountant.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orgAccountant.example.com
      - CORE_PEER_ADDRESS=peer1.orgAccountant.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.orgAccountant.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgAccountant.example.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgAccountant.example.com:7051
      - CORE_PEER_LOCALMSPID=OrgAccountantMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/orgAccountant.example.com/peers/peer1.orgAccountant.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgAccountant.example.com/peers/peer1.orgAccountant.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.orgAccountant.example.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.orgStaff.example.com:
    container_name: peer0.orgStaff.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orgStaff.example.com
      - CORE_PEER_ADDRESS=peer0.orgStaff.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgStaff.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgStaff.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgStaff.example.com:10051
      - CORE_PEER_LOCALMSPID=OrgStaffMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/orgStaff.example.com/peers/peer0.orgStaff.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgStaff.example.com/peers/peer0.orgStaff.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.orgStaff.example.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.orgStaff.example.com:
    container_name: peer1.orgStaff.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orgStaff.example.com
      - CORE_PEER_ADDRESS=peer1.orgStaff.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.orgStaff.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgStaff.example.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgStaff.example.com:9051
      - CORE_PEER_LOCALMSPID=OrgStaffMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/orgStaff.example.com/peers/peer1.orgStaff.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgStaff.example.com/peers/peer1.orgStaff.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.orgStaff.example.com:/var/hyperledger/production
    ports:
      - 10051:10051
      
  peer0.orgManager.example.com:
    container_name: peer0.orgManager.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orgManager.example.com
      - CORE_PEER_ADDRESS=peer0.orgManager.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgManager.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgManager.example.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgManager.example.com:11051
      - CORE_PEER_LOCALMSPID=OrgManagerMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/orgManager.example.com/peers/peer0.orgManager.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgManager.example.com/peers/peer0.orgManager.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.orgManager.example.com:/var/hyperledger/production
    ports:
      - 11051:11051
    networks:
      - byfn
      
  peer1.orgManager.example.com:
    container_name: peer1.orgManager.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orgManager.example.com
      - CORE_PEER_ADDRESS=peer1.orgManager.example.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.orgManager.example.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgManager.example.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgManager.example.com:12051
      - CORE_PEER_LOCALMSPID=OrgManagerMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/orgManager.example.com/peers/peer1.orgManager.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgManager.example.com/peers/peer1.orgManager.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.orgManager.example.com:/var/hyperledger/production
    ports:
      - 12051:12051
    networks:
      - byfn
